# Generated by Django 5.0.4 on 2024-05-02 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carritoitem',
            old_name='id_carrito',
            new_name='carrito',
        ),
        migrations.RenameField(
            model_name='ciudad',
            old_name='id_departamento',
            new_name='departamento',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='id_ciudad',
            new_name='ciudad',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='id_departamento',
            new_name='departamento',
        ),
        migrations.RenameField(
            model_name='documento',
            old_name='id_cliente',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='ordenitem',
            old_name='id_orden',
            new_name='orden',
        ),
        migrations.RenameField(
            model_name='ordenitem',
            old_name='id_producto',
            new_name='producto',
        ),
        migrations.RenameField(
            model_name='telefono',
            old_name='id_cliente',
            new_name='cliente',
        ),
    ]
