# Generated by Django 5.0.6 on 2024-05-29 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_remove_cliente_contrasena_cliente_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='last_login',
            field=models.DateTimeField(auto_now_add=True, default='2024-05-29 20:19:08.438230'),
            preserve_default=False,
        ),
    ]
